### ISSUE TITLE
d3d11createdevice()error

### ISSUE THREAD

**Issue by spotanjo3** [shimazzz/SEGASaturnEmulator-SSF#27]
I got a d3d11createdevice()error here, And I am on Intel HD 3000 video card. PCSX2 Emulator runs pretty well on my LAPTOP.

**Comment by spotanjo3** [comment]
Hello?

**Comment by spotanjo3** [comment]
I have a problem with SSF emulator. 

My old version is:
SSF v0.12 beta R4 and worked just fine. It was outdated but worked fine for me. No error.

SSF_PreviewVer_R28 is the latest version and I got an error: D3D11CreateDevice() error. How do I resolve it ? Remember, SSF v0.11 beta R4 works fine for me. Weird.

**Comment by pal1000** [comment]
The test versions have gradually increased Direct3D feature level requirements to 10.1 at first and then 11.0. The second bump goes beyond what Intel HD Graphics 3000 driver can manage. PCSX2 only requires feature level 10.0 so iit still works. If your CPU has 4 threads and 3 GHz or higher you can attempt ruining SSF with software rasterization.

**Comment by spotanjo3** [comment]
You are too late. But thanks anyway. I am going to closed it.
